#!/usr/bin/env bash
# journal_append.sh — append exactly one conformant line to journal.jsonl.
# Run with: bash journal_append.sh --task <id> --event <shape> [field flags]
#
# WHY THIS EXISTS. The documented idiom used to be a printf of a command
# substitution:
#
#     printf '%s\n' "$(jq -nc --arg ts "$(date -u +%FT%TZ)" ...)" >> journal.jsonl
#
# A worktree-isolated session refuses to run that. The harness guard cannot
# verify that a compound command containing substitutions stays inside the
# worktree, so it declines the call outright — five of six lanes in one parallel
# batch hit it. The dangerous part was not the retries. One lane worked around
# the refusal by calling `date -u` once and hand-writing the rest of its
# timestamps as estimates: an accurate event ordering with a fictional clock,
# and nothing downstream could tell. A journal whose whole value is being
# evidence must not have a guessable `ts`.
#
# So the substitution moves in here, where it is ordinary shell, and the
# caller's argv stays flat: flags in, one line out.
#
# THIS IS NOT A WRITER ENGINE. references/journal.md refuses a log framework —
# rotation, readers, query tools — and still does. This is an argv-to-JSON shim
# of the same shape lib/run_gates.sh and lib/detect_stage.sh already have:
# arguments in, a contract out, no state.
#
# ts IS NEVER A PARAMETER. `--ts` is refused rather than ignored, because a
# caller who passed one and saw no error would believe it took effect.
#
# Requires jq (already a hard dependency of scripts/verify.sh).
#
# Exit codes: 0 = one line appended · 2 = usage, environment, or a refused flag.
# Nothing is appended on any non-zero exit.
set -uo pipefail

die() { printf 'journal_append: %s\n' "$1" >&2; exit 2; }

usage() {
  cat >&2 <<'USAGE'
journal_append.sh --task <id> --event <stage|phase|gate|decision|escalation> [flags]

  Common:      --task <id>   --file <path>   (default: journal.jsonl at the repo/worktree root)
  stage:       --to <name> [--from <name>] [--mode <mode>]
  phase:       --phase <name> --result <ok|failed|refused> [--summary <text>]
               [--agent <name> ...] [--artifact <path> ...]
  gate:        --result <pass|fail|no-gates> --exit <n> [--attempt <n>]
               [--check <name> ...] [--artifact <path> ...]
  decision:    --stage <name> --question <text> --answer <text>
  escalation:  --stage <name> --reason <slug> --status <status> [--detail <text> ...]

`ts` is generated by this script; --ts is refused.
USAGE
  exit 2
}

command -v jq >/dev/null 2>&1 || die "jq is required but was not found on PATH"

# --- parse -------------------------------------------------------------------
#
# Values are collected into scalars, and the four repeatable flags into arrays.
# SET_FLAGS records which flags were actually given, so the shape check below
# can tell "omitted" from "given empty" and reject a flag that does not belong
# to the event. It is a space-delimited string rather than a set, because bash
# 3.2 (the floor tests/lib.sh pins) has no associative arrays.

TASK='' EVENT='' FILE=''
FROM='' TO='' MODE='' PHASE='' RESULT='' SUMMARY='' STAGE=''
QUESTION='' ANSWER='' REASON='' STATUS='' EXIT_CODE='' ATTEMPT=''
AGENTS=() ARTIFACTS=() CHECKS=() DETAILS=()
SET_FLAGS=' '

mark() { SET_FLAGS="$SET_FLAGS$1 "; }
was_set() { case "$SET_FLAGS" in *" $1 "*) return 0 ;; *) return 1 ;; esac; }

need_value() {  # need_value <flag> <count-of-remaining-args>
  [ "$2" -ge 2 ] || die "$1 requires a value"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --task)     need_value "$1" "$#"; TASK="$2";      mark task;     shift 2 ;;
    --event)    need_value "$1" "$#"; EVENT="$2";     mark event;    shift 2 ;;
    --file)
      need_value "$1" "$#"
      # An explicit empty value must not read as "not given": that would fall
      # through to the default and write into a live run's journal while the
      # caller believed it had redirected the line elsewhere.
      [ -n "$2" ] || die "--file was given an empty value"
      FILE="$2"; mark file; shift 2 ;;
    --from)     need_value "$1" "$#"; FROM="$2";      mark from;     shift 2 ;;
    --to)       need_value "$1" "$#"; TO="$2";        mark to;       shift 2 ;;
    --mode)     need_value "$1" "$#"; MODE="$2";      mark mode;     shift 2 ;;
    --phase)    need_value "$1" "$#"; PHASE="$2";     mark phase;    shift 2 ;;
    --result)   need_value "$1" "$#"; RESULT="$2";    mark result;   shift 2 ;;
    --summary)  need_value "$1" "$#"; SUMMARY="$2";   mark summary;  shift 2 ;;
    --stage)    need_value "$1" "$#"; STAGE="$2";     mark stage;    shift 2 ;;
    --question) need_value "$1" "$#"; QUESTION="$2";  mark question; shift 2 ;;
    --answer)   need_value "$1" "$#"; ANSWER="$2";    mark answer;   shift 2 ;;
    --reason)   need_value "$1" "$#"; REASON="$2";    mark reason;   shift 2 ;;
    --status)   need_value "$1" "$#"; STATUS="$2";    mark status;   shift 2 ;;
    --exit)     need_value "$1" "$#"; EXIT_CODE="$2"; mark exit;     shift 2 ;;
    --attempt)  need_value "$1" "$#"; ATTEMPT="$2";   mark attempt;  shift 2 ;;
    --agent)    need_value "$1" "$#"; AGENTS[${#AGENTS[@]}]="$2";       mark agent;    shift 2 ;;
    --artifact) need_value "$1" "$#"; ARTIFACTS[${#ARTIFACTS[@]}]="$2"; mark artifact; shift 2 ;;
    --check)    need_value "$1" "$#"; CHECKS[${#CHECKS[@]}]="$2";       mark check;    shift 2 ;;
    --detail)   need_value "$1" "$#"; DETAILS[${#DETAILS[@]}]="$2";     mark detail;   shift 2 ;;
    --ts)
      die "--ts is not accepted: ts is generated by this script, so that a line cannot carry a time its author chose" ;;
    -h|--help) usage ;;
    *) die "unknown argument: $1" ;;
  esac
done

[ -n "$TASK" ]  || die "--task is required"
[ -n "$EVENT" ] || die "--event is required"

# --- shape -------------------------------------------------------------------
#
# Per-event required and permitted fields, from references/journal.md. Enforcing
# them here is what makes "emitted with the fields its shape specifies" a
# property of the script rather than of the particular calls a test happens to
# make. Adding an event means adding a row here AND a shape in that document.

case "$EVENT" in
  stage)      REQUIRED='to';                    PERMITTED='from to mode' ;;
  phase)      REQUIRED='phase result';          PERMITTED='phase result summary agent artifact' ;;
  gate)       REQUIRED='result exit';           PERMITTED='result exit attempt check artifact' ;;
  decision)   REQUIRED='stage question answer'; PERMITTED='stage question answer' ;;
  escalation) REQUIRED='stage reason status';   PERMITTED='stage reason status detail' ;;
  *) die "unknown --event: $EVENT (expected stage, phase, gate, decision or escalation)" ;;
esac

for f in $REQUIRED; do
  was_set "$f" || die "--event $EVENT requires --$f"
done

# Everything given must be permitted by the shape, or common to all events.
for f in $SET_FLAGS; do
  case " task event file $PERMITTED " in
    *" $f "*) ;;
    *) die "--$f is not a field of the $EVENT event" ;;
  esac
done

# The enumerated values are normative in references/journal.md, and an
# unrecognised --event is already exit 2 for the same reason: a line whose
# `result` reads `passed` is not a query away from `pass`, it is invisible to
# it. Enforcing the values costs nothing and removes an inconsistency between
# what usage() advertises and what the script accepts.
case "$EVENT" in
  phase)
    case "$RESULT" in
      ok|failed|refused) ;;
      *) die "--result for a phase event must be ok, failed or refused, got: $RESULT" ;;
    esac ;;
  gate)
    case "$RESULT" in
      pass|fail|no-gates) ;;
      *) die "--result for a gate event must be pass, fail or no-gates, got: $RESULT" ;;
    esac ;;
esac

is_int() {  # a bare integer, optionally negative; "1-2" and "" are not integers
  case "$1" in
    ''|-) return 1 ;;
    -*) case "${1#-}" in ''|*[!0-9]*) return 1 ;; *) return 0 ;; esac ;;
    *)  case "$1"      in    *[!0-9]*) return 1 ;; *) return 0 ;; esac ;;
  esac
}
if was_set exit;    then is_int "$EXIT_CODE" || die "--exit must be an integer, got: $EXIT_CODE"; fi
if was_set attempt; then is_int "$ATTEMPT"   || die "--attempt must be an integer, got: $ATTEMPT"; fi

# --- destination -------------------------------------------------------------
#
# The default is the root of the tree the call is made FROM. In a linked
# worktree that is the worktree, which is where the run's own journal belongs —
# resolving it any other way would send every parallel lane's events into the
# main checkout's file, where the shared exclude then hides them.

if [ -z "$FILE" ]; then
  root="$(git rev-parse --show-toplevel 2>/dev/null)" \
    || die "not inside a git repository; pass --file to say where the journal is"
  FILE="$root/journal.jsonl"
fi

# --- build -------------------------------------------------------------------
#
# Arrays are accumulated one element at a time. `jq --args`/$ARGS.positional is
# a single flat list, so it cannot keep four arrays apart, and its interaction
# with `--` varies between jq versions in a way that yields an empty array
# rather than an error. This form needs only --arg/--argjson.

json_array() {  # json_array <values...> — echo a compact JSON array
  local acc='[]' v
  for v in "$@"; do
    acc="$(jq -nc --argjson acc "$acc" --arg v "$v" '$acc + [$v]')" || return 1
  done
  printf '%s' "$acc"
}

# On bash 3.2, "${arr[@]}" on an EMPTY array under `set -u` is a fatal
# unbound-variable error rather than an empty expansion. Every expansion below
# is therefore guarded by its own count.
agents_json='[]'; artifacts_json='[]'; checks_json='[]'; details_json='[]'
if [ "${#AGENTS[@]}"    -gt 0 ]; then agents_json="$(json_array "${AGENTS[@]}")"       || die "jq failed building agents"; fi
if [ "${#ARTIFACTS[@]}" -gt 0 ]; then artifacts_json="$(json_array "${ARTIFACTS[@]}")" || die "jq failed building artifacts"; fi
if [ "${#CHECKS[@]}"    -gt 0 ]; then checks_json="$(json_array "${CHECKS[@]}")"       || die "jq failed building checks"; fi
if [ "${#DETAILS[@]}"   -gt 0 ]; then details_json="$(json_array "${DETAILS[@]}")"     || die "jq failed building detail"; fi

TS="$(date -u +%FT%TZ)"

# Field order follows the documented examples: ts, task, event, then the shape's
# own fields. jq preserves object construction order, so the filter is built in
# that order too.
FILTER='{ts:$ts,task:$task,event:$event}'
set -- --arg ts "$TS" --arg task "$TASK" --arg event "$EVENT"

case "$EVENT" in
  stage)
    # `from` is null on the first line of a run, and the key is always present.
    if was_set from; then
      FILTER="$FILTER+{from:\$from}"; set -- "$@" --arg from "$FROM"
    else
      FILTER="$FILTER+{from:null}"
    fi
    FILTER="$FILTER+{to:\$to}"; set -- "$@" --arg to "$TO"
    if was_set mode; then FILTER="$FILTER+{mode:\$mode}"; set -- "$@" --arg mode "$MODE"; fi
    ;;
  phase)
    FILTER="$FILTER+{phase:\$phase}+{agents:\$agents}+{result:\$result}"
    set -- "$@" --arg phase "$PHASE" --argjson agents "$agents_json" --arg result "$RESULT"
    if was_set summary; then FILTER="$FILTER+{summary:\$summary}"; set -- "$@" --arg summary "$SUMMARY"; fi
    FILTER="$FILTER+{artifacts:\$artifacts}"; set -- "$@" --argjson artifacts "$artifacts_json"
    ;;
  gate)
    FILTER="$FILTER+{result:\$result}+{exit:\$exit}"
    set -- "$@" --arg result "$RESULT" --argjson exit "$EXIT_CODE"
    if was_set attempt; then FILTER="$FILTER+{attempt:\$attempt}"; set -- "$@" --argjson attempt "$ATTEMPT"; fi
    FILTER="$FILTER+{checks:\$checks}+{artifacts:\$artifacts}"
    set -- "$@" --argjson checks "$checks_json" --argjson artifacts "$artifacts_json"
    ;;
  decision)
    FILTER="$FILTER+{stage:\$stage}+{question:\$question}+{answer:\$answer}"
    set -- "$@" --arg stage "$STAGE" --arg question "$QUESTION" --arg answer "$ANSWER"
    ;;
  escalation)
    FILTER="$FILTER+{stage:\$stage}+{reason:\$reason}+{detail:\$detail}+{status:\$status}"
    set -- "$@" --arg stage "$STAGE" --arg reason "$REASON" \
                --argjson detail "$details_json" --arg status "$STATUS"
    ;;
esac

# jq's status is checked BEFORE the append. Without this a jq failure leaves an
# empty capture and the printf still fires, writing a blank line the caller
# believes is an event.
LINE="$(jq -nc "$@" "$FILTER")" || die "jq failed to build the $EVENT line"
[ -n "$LINE" ] || die "jq produced an empty line for the $EVENT event"

# --- append ------------------------------------------------------------------
#
# One append, and no rewrite path exists anywhere in this script. That is how
# append-only is guaranteed rather than asserted.
printf '%s\n' "$LINE" >> "$FILE" || die "could not append to $FILE"
